cover.order<-function(x, if.decreasing){
  return(x[order(abs(x-0.95),decreasing = if.decreasing)])
}

sub.data$OW.RMSE.ASCE3=sort(sub.data$OW.RMSE.ASCE3, decreasing = if.decreasing)
sub.data$IPW.RMSE.ASCE3=sort(sub.data$IPW.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.ASCE3=sort(sub.data$COX.Q.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.ASCE3=sort(sub.data$COX.MSM.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.ASCE3=sort(sub.data$OW.AIPW.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.ASCE3=sort(sub.data$IPW.AIPW.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$OWG.RMSE.ASCE3=sort(sub.data$OWG.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$IPWG.RMSE.ASCE3=sort(sub.data$IPWG.RMSE.ASCE3,decreasing = if.decreasing)

sub.data$OW.RMSE.RACE3=sort(sub.data$OW.RMSE.RACE3, decreasing = if.decreasing)
sub.data$IPW.RMSE.RACE3=sort(sub.data$IPW.RMSE.RACE3,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.RACE3=sort(sub.data$COX.Q.RMSE.RACE3,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.RACE3=sort(sub.data$COX.MSM.RMSE.RACE3,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.RACE3=sort(sub.data$OW.AIPW.RMSE.RACE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.RACE3=sort(sub.data$IPW.AIPW.RMSE.RACE3,decreasing = if.decreasing)
sub.data$OWG.RMSE.RACE3=sort(sub.data$OWG.RMSE.RACE3,decreasing = if.decreasing)
sub.data$IPWG.RMSE.RACE3=sort(sub.data$IPWG.RMSE.RACE3,decreasing = if.decreasing)

sub.data$OW.RMSE.SPCE3=sort(sub.data$OW.RMSE.SPCE3, decreasing = if.decreasing)
sub.data$IPW.RMSE.SPCE3=sort(sub.data$IPW.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.SPCE3=sort(sub.data$COX.Q.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.SPCE3=sort(sub.data$COX.MSM.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.SPCE3=sort(sub.data$OW.AIPW.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.SPCE3=sort(sub.data$IPW.AIPW.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$OWG.RMSE.SPCE3=sort(sub.data$OWG.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$IPWG.RMSE.SPCE3=sort(sub.data$IPWG.RMSE.SPCE3,decreasing = if.decreasing)

sub.data$OW.BIAS.ASCE3=sort(sub.data$OW.BIAS.ASCE3, decreasing = if.decreasing)
sub.data$IPW.BIAS.ASCE3=sort(sub.data$IPW.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.ASCE3=sort(sub.data$COX.Q.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.ASCE3=sort(sub.data$COX.MSM.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.ASCE3=sort(sub.data$OW.AIPW.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.ASCE3=sort(sub.data$IPW.AIPW.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$OWG.BIAS.ASCE3=sort(sub.data$OWG.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$IPWG.BIAS.ASCE3=sort(sub.data$IPWG.BIAS.ASCE3,decreasing = if.decreasing)

sub.data$OW.BIAS.RACE3=sort(sub.data$OW.BIAS.RACE3, decreasing = if.decreasing)
sub.data$IPW.BIAS.RACE3=sort(sub.data$IPW.BIAS.RACE3,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.RACE3=sort(sub.data$COX.Q.BIAS.RACE3,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.RACE3=sort(sub.data$COX.MSM.BIAS.RACE3,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.RACE3=sort(sub.data$OW.AIPW.BIAS.RACE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.RACE3=sort(sub.data$IPW.AIPW.BIAS.RACE3,decreasing = if.decreasing)
sub.data$OWG.BIAS.RACE3=sort(sub.data$OWG.BIAS.RACE3,decreasing = if.decreasing)
sub.data$IPWG.BIAS.RACE3=sort(sub.data$IPWG.BIAS.RACE3,decreasing = if.decreasing)

sub.data$OW.BIAS.SPCE3=sort(sub.data$OW.BIAS.SPCE3, decreasing = if.decreasing)
sub.data$IPW.BIAS.SPCE3=sort(sub.data$IPW.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.SPCE3=sort(sub.data$COX.Q.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.SPCE3=sort(sub.data$COX.MSM.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.SPCE3=sort(sub.data$OW.AIPW.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.SPCE3=sort(sub.data$IPW.AIPW.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$OWG.BIAS.SPCE3=sort(sub.data$OWG.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$IPWG.BIAS.SPCE3=sort(sub.data$IPWG.BIAS.SPCE3,decreasing = if.decreasing)

sub.data$OW.COVER.ASCE3=cover.order(sub.data$OW.COVER.ASCE3, if.decreasing)
sub.data$IPW.COVER.ASCE3=cover.order(sub.data$IPW.COVER.ASCE3, if.decreasing)
sub.data$COX.Q.COVER.ASCE3=cover.order(sub.data$COX.Q.COVER.ASCE3, if.decreasing)
sub.data$COX.MSM.COVER.ASCE3=cover.order(sub.data$COX.MSM.COVER.ASCE3, if.decreasing)
sub.data$OW.AIPW.COVER.ASCE3=cover.order(sub.data$OW.AIPW.COVER.ASCE3, if.decreasing)
sub.data$IPW.AIPW.COVER.ASCE3=cover.order(sub.data$IPW.AIPW.COVER.ASCE3, if.decreasing)
sub.data$OWG.COVER.ASCE3=cover.order(sub.data$OWG.COVER.ASCE3, if.decreasing)
sub.data$IPWG.COVER.ASCE3=cover.order(sub.data$IPWG.COVER.ASCE3, if.decreasing)

sub.data$OW.COVER.RACE3=cover.order(sub.data$OW.COVER.RACE3, if.decreasing)
sub.data$IPW.COVER.RACE3=cover.order(sub.data$IPW.COVER.RACE3, if.decreasing)
sub.data$COX.Q.COVER.RACE3=cover.order(sub.data$COX.Q.COVER.RACE3, if.decreasing)
sub.data$COX.MSM.COVER.RACE3=cover.order(sub.data$COX.MSM.COVER.RACE3, if.decreasing)
sub.data$OW.AIPW.COVER.RACE3=cover.order(sub.data$OW.AIPW.COVER.RACE3, if.decreasing)
sub.data$IPW.AIPW.COVER.RACE3=cover.order(sub.data$IPW.AIPW.COVER.RACE3, if.decreasing)
sub.data$OWG.COVER.RACE3=cover.order(sub.data$OWG.COVER.RACE3, if.decreasing)
sub.data$IPWG.COVER.RACE3=cover.order(sub.data$IPWG.COVER.RACE3, if.decreasing)

sub.data$OW.COVER.SPCE3=cover.order(sub.data$OW.COVER.SPCE3, if.decreasing)
sub.data$IPW.COVER.SPCE3=cover.order(sub.data$IPW.COVER.SPCE3, if.decreasing)
sub.data$COX.Q.COVER=cover.order(sub.data$COX.Q.COVER.SPCE3, if.decreasing)
sub.data$COX.MSM.COVER.SPCE3=cover.order(sub.data$COX.MSM.COVER.SPCE3, if.decreasing)
sub.data$OW.AIPW.COVER.SPCE3=cover.order(sub.data$OW.AIPW.COVER.SPCE3, if.decreasing)
sub.data$IPW.AIPW.COVER.SPCE3=cover.order(sub.data$IPW.AIPW.COVER.SPCE3, if.decreasing)
sub.data$OWG.COVER.SPCE3=cover.order(sub.data$OWG.COVER.SPCE3, if.decreasing)
sub.data$IPWG.COVER.SPCE3=cover.order(sub.data$IPWG.COVER.SPCE3, if.decreasing)

sub.data$OW.RMSE.ASCE2=sort(sub.data$OW.RMSE.ASCE2, decreasing = if.decreasing)
sub.data$IPW.RMSE.ASCE2=sort(sub.data$IPW.RMSE.ASCE2,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.ASCE2=sort(sub.data$COX.Q.RMSE.ASCE2,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.ASCE2=sort(sub.data$COX.MSM.RMSE.ASCE2,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.ASCE2=sort(sub.data$OW.AIPW.RMSE.ASCE2,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.ASCE2=sort(sub.data$IPW.AIPW.RMSE.ASCE2,decreasing = if.decreasing)
sub.data$OWG.RMSE.ASCE2=sort(sub.data$OWG.RMSE.ASCE2,decreasing = if.decreasing)
sub.data$IPWG.RMSE.ASCE2=sort(sub.data$IPWG.RMSE.ASCE2,decreasing = if.decreasing)

sub.data$OW.RMSE.RACE2=sort(sub.data$OW.RMSE.RACE2, decreasing = if.decreasing)
sub.data$IPW.RMSE.RACE2=sort(sub.data$IPW.RMSE.RACE2,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.RACE2=sort(sub.data$COX.Q.RMSE.RACE2,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.RACE2=sort(sub.data$COX.MSM.RMSE.RACE2,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.RACE2=sort(sub.data$OW.AIPW.RMSE.RACE2,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.RACE2=sort(sub.data$IPW.AIPW.RMSE.RACE2,decreasing = if.decreasing)
sub.data$OWG.RMSE.RACE2=sort(sub.data$OWG.RMSE.RACE2,decreasing = if.decreasing)
sub.data$IPWG.RMSE.RACE2=sort(sub.data$IPWG.RMSE.RACE2,decreasing = if.decreasing)

sub.data$OW.RMSE.SPCE2=sort(sub.data$OW.RMSE.SPCE2, decreasing = if.decreasing)
sub.data$IPW.RMSE.SPCE2=sort(sub.data$IPW.RMSE.SPCE2,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.SPCE2=sort(sub.data$COX.Q.RMSE.SPCE2,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.SPCE2=sort(sub.data$COX.MSM.RMSE.SPCE2,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.SPCE2=sort(sub.data$OW.AIPW.RMSE.SPCE2,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.SPCE2=sort(sub.data$IPW.AIPW.RMSE.SPCE2,decreasing = if.decreasing)
sub.data$OWG.RMSE.SPCE2=sort(sub.data$OWG.RMSE.SPCE2,decreasing = if.decreasing)
sub.data$IPWG.RMSE.SPCE2=sort(sub.data$IPWG.RMSE.SPCE2,decreasing = if.decreasing)

sub.data$OW.BIAS.ASCE2=sort(sub.data$OW.BIAS.ASCE2, decreasing = if.decreasing)
sub.data$IPW.BIAS.ASCE2=sort(sub.data$IPW.BIAS.ASCE2,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.ASCE2=sort(sub.data$COX.Q.BIAS.ASCE2,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.ASCE2=sort(sub.data$COX.MSM.BIAS.ASCE2,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.ASCE2=sort(sub.data$OW.AIPW.BIAS.ASCE2,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.ASCE2=sort(sub.data$IPW.AIPW.BIAS.ASCE2,decreasing = if.decreasing)
sub.data$OWG.BIAS.ASCE2=sort(sub.data$OWG.BIAS.ASCE2,decreasing = if.decreasing)
sub.data$IPWG.BIAS.ASCE2=sort(sub.data$IPWG.BIAS.ASCE2,decreasing = if.decreasing)

sub.data$OW.RMSE.ASCE1=sort(sub.data$OW.RMSE.ASCE1, decreasing = if.decreasing)
sub.data$IPW.RMSE.ASCE1=sort(sub.data$IPW.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.ASCE1=sort(sub.data$COX.Q.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.ASCE1=sort(sub.data$COX.MSM.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.ASCE1=sort(sub.data$OW.AIPW.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.ASCE1=sort(sub.data$IPW.AIPW.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$OWG.RMSE.ASCE1=sort(sub.data$OWG.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$IPWG.RMSE.ASCE1=sort(sub.data$IPWG.RMSE.ASCE1,decreasing = if.decreasing)

sub.data$OW.RMSE.RACE1=sort(sub.data$OW.RMSE.RACE1, decreasing = if.decreasing)
sub.data$IPW.RMSE.RACE1=sort(sub.data$IPW.RMSE.RACE1,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.RACE1=sort(sub.data$COX.Q.RMSE.RACE1,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.RACE1=sort(sub.data$COX.MSM.RMSE.RACE1,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.RACE1=sort(sub.data$OW.AIPW.RMSE.RACE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.RACE1=sort(sub.data$IPW.AIPW.RMSE.RACE1,decreasing = if.decreasing)
sub.data$OWG.RMSE.RACE1=sort(sub.data$OWG.RMSE.RACE1,decreasing = if.decreasing)
sub.data$IPWG.RMSE.RACE1=sort(sub.data$IPWG.RMSE.RACE1,decreasing = if.decreasing)

sub.data$OW.RMSE.SPCE1=sort(sub.data$OW.RMSE.SPCE1, decreasing = if.decreasing)
sub.data$IPW.RMSE.SPCE1=sort(sub.data$IPW.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.SPCE1=sort(sub.data$COX.Q.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.SPCE1=sort(sub.data$COX.MSM.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.SPCE1=sort(sub.data$OW.AIPW.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.SPCE1=sort(sub.data$IPW.AIPW.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$OWG.RMSE.SPCE1=sort(sub.data$OWG.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$IPWG.RMSE.SPCE1=sort(sub.data$IPWG.RMSE.SPCE1,decreasing = if.decreasing)

sub.data$OW.BIAS.ASCE1=sort(sub.data$OW.BIAS.ASCE1, decreasing = if.decreasing)
sub.data$IPW.BIAS.ASCE1=sort(sub.data$IPW.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.ASCE1=sort(sub.data$COX.Q.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.ASCE1=sort(sub.data$COX.MSM.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.ASCE1=sort(sub.data$OW.AIPW.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.ASCE1=sort(sub.data$IPW.AIPW.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$OWG.BIAS.ASCE1=sort(sub.data$OWG.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$IPWG.BIAS.ASCE1=sort(sub.data$IPWG.BIAS.ASCE1,decreasing = if.decreasing)

sub.data$OW.BIAS.RACE1=sort(sub.data$OW.BIAS.RACE1, decreasing = if.decreasing)
sub.data$IPW.BIAS.RACE1=sort(sub.data$IPW.BIAS.RACE1,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.RACE1=sort(sub.data$COX.Q.BIAS.RACE1,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.RACE1=sort(sub.data$COX.MSM.BIAS.RACE1,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.RACE1=sort(sub.data$OW.AIPW.BIAS.RACE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.RACE1=sort(sub.data$IPW.AIPW.BIAS.RACE1,decreasing = if.decreasing)
sub.data$OWG.BIAS.RACE1=sort(sub.data$OWG.BIAS.RACE1,decreasing = if.decreasing)
sub.data$IPWG.BIAS.RACE1=sort(sub.data$IPWG.BIAS.RACE1,decreasing = if.decreasing)

sub.data$OW.BIAS.SPCE1=sort(sub.data$OW.BIAS.SPCE1, decreasing = if.decreasing)
sub.data$IPW.BIAS.SPCE1=sort(sub.data$IPW.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.SPCE1=sort(sub.data$COX.Q.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.SPCE1=sort(sub.data$COX.MSM.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.SPCE1=sort(sub.data$OW.AIPW.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.SPCE1=sort(sub.data$IPW.AIPW.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$OWG.BIAS.SPCE1=sort(sub.data$OWG.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$IPWG.BIAS.SPCE1=sort(sub.data$IPWG.BIAS.SPCE1,decreasing = if.decreasing)

sub.data$OW.COVER.ASCE1=cover.order(sub.data$OW.COVER.ASCE1, if.decreasing)
sub.data$IPW.COVER.ASCE1=cover.order(sub.data$IPW.COVER.ASCE1, if.decreasing)
sub.data$COX.Q.COVER.ASCE1=cover.order(sub.data$COX.Q.COVER.ASCE1, if.decreasing)
sub.data$COX.MSM.COVER.ASCE1=cover.order(sub.data$COX.MSM.COVER.ASCE1, if.decreasing)
sub.data$OW.AIPW.COVER.ASCE1=cover.order(sub.data$OW.AIPW.COVER.ASCE1, if.decreasing)
sub.data$IPW.AIPW.COVER.ASCE1=cover.order(sub.data$IPW.AIPW.COVER.ASCE1, if.decreasing)
sub.data$OWG.COVER.ASCE1=cover.order(sub.data$OWG.COVER.ASCE1, if.decreasing)
sub.data$IPWG.COVER.ASCE1=cover.order(sub.data$IPWG.COVER.ASCE1, if.decreasing)

sub.data$OW.COVER.RACE1=cover.order(sub.data$OW.COVER.RACE1, if.decreasing)
sub.data$IPW.COVER.RACE1=cover.order(sub.data$IPW.COVER.RACE1, if.decreasing)
sub.data$COX.Q.COVER.RACE1=cover.order(sub.data$COX.Q.COVER.RACE1, if.decreasing)
sub.data$COX.MSM.COVER.RACE1=cover.order(sub.data$COX.MSM.COVER.RACE1, if.decreasing)
sub.data$OW.AIPW.COVER.RACE1=cover.order(sub.data$OW.AIPW.COVER.RACE1, if.decreasing)
sub.data$IPW.AIPW.COVER.RACE1=cover.order(sub.data$IPW.AIPW.COVER.RACE1, if.decreasing)
sub.data$OWG.COVER.RACE1=cover.order(sub.data$OWG.COVER.RACE1, if.decreasing)
sub.data$IPWG.COVER.RACE1=cover.order(sub.data$IPWG.COVER.RACE1, if.decreasing)

sub.data$OW.COVER.SPCE1=cover.order(sub.data$OW.COVER.SPCE1, if.decreasing)
sub.data$IPW.COVER.SPCE1=cover.order(sub.data$IPW.COVER.SPCE1, if.decreasing)
sub.data$COX.Q.COVER=cover.order(sub.data$COX.Q.COVER.SPCE1, if.decreasing)
sub.data$COX.MSM.COVER.SPCE1=cover.order(sub.data$COX.MSM.COVER.SPCE1, if.decreasing)
sub.data$OW.AIPW.COVER.SPCE1=cover.order(sub.data$OW.AIPW.COVER.SPCE1, if.decreasing)
sub.data$IPW.AIPW.COVER.SPCE1=cover.order(sub.data$IPW.AIPW.COVER.SPCE1, if.decreasing)
sub.data$OWG.COVER.SPCE1=cover.order(sub.data$OWG.COVER.SPCE1, if.decreasing)
sub.data$IPWG.COVER.SPCE1=cover.order(sub.data$IPWG.COVER.SPCE1, if.decreasing)
