cover.order<-function(x, decreasing){
  return(x[order(abs(x-0.95),decreasing = decreasing)])
}

sub.data$OW.RMSE.ASCE3=sort(sub.data$OW.RMSE.ASCE3, decreasing = if.decreasing)
sub.data$IPW.RMSE.ASCE3=sort(sub.data$IPW.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.ASCE3=sort(sub.data$COX.Q.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.ASCE3=sort(sub.data$COX.MSM.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.ASCE3=sort(sub.data$OW.AIPW.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.ASCE3=sort(sub.data$IPW.AIPW.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$OWG.RMSE.ASCE3=sort(sub.data$OWG.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$IPWG.RMSE.ASCE3=sort(sub.data$IPWG.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.RMSE.ASCE3=sort(sub.data$PSEUDO.UNADJ.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$PSEUDO.G.RMSE.ASCE3=sort(sub.data$PSEUDO.G.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.RMSE.ASCE3=sort(sub.data$IPW.UNTRIM.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$IPW.MAO.RMSE.ASCE3=sort(sub.data$IPW.MAO.RMSE.ASCE3,decreasing = if.decreasing)
sub.data$OW.MAO.RMSE.ASCE3=sort(sub.data$OW.MAO.RMSE.ASCE3,decreasing = if.decreasing)


sub.data$OW.RMSE.RACE3=sort(sub.data$OW.RMSE.RACE3, decreasing = if.decreasing)
sub.data$IPW.RMSE.RACE3=sort(sub.data$IPW.RMSE.RACE3,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.RACE3=sort(sub.data$COX.Q.RMSE.RACE3,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.RACE3=sort(sub.data$COX.MSM.RMSE.RACE3,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.RACE3=sort(sub.data$OW.AIPW.RMSE.RACE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.RACE3=sort(sub.data$IPW.AIPW.RMSE.RACE3,decreasing = if.decreasing)
sub.data$OWG.RMSE.RACE3=sort(sub.data$OWG.RMSE.RACE3,decreasing = if.decreasing)
sub.data$IPWG.RMSE.RACE3=sort(sub.data$IPWG.RMSE.RACE3,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.RMSE.RACE3=sort(sub.data$PSEUDO.UNADJ.RMSE.RACE3,decreasing = if.decreasing)
sub.data$PSEUDO.G.RMSE.RACE3=sort(sub.data$PSEUDO.G.RMSE.RACE3,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.RMSE.RACE3=sort(sub.data$IPW.UNTRIM.RMSE.RACE3,decreasing = if.decreasing)
sub.data$IPW.MAO.RMSE.RACE3=sort(sub.data$IPW.MAO.RMSE.RACE3,decreasing = if.decreasing)
sub.data$OW.MAO.RMSE.RACE3=sort(sub.data$OW.MAO.RMSE.RACE3,decreasing = if.decreasing)

sub.data$OW.RMSE.SPCE3=sort(sub.data$OW.RMSE.SPCE3, decreasing = if.decreasing)
sub.data$IPW.RMSE.SPCE3=sort(sub.data$IPW.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.SPCE3=sort(sub.data$COX.Q.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.SPCE3=sort(sub.data$COX.MSM.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.SPCE3=sort(sub.data$OW.AIPW.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.SPCE3=sort(sub.data$IPW.AIPW.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$OWG.RMSE.SPCE3=sort(sub.data$OWG.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$IPWG.RMSE.SPCE3=sort(sub.data$IPWG.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.RMSE.SPCE3=sort(sub.data$PSEUDO.UNADJ.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$PSEUDO.G.RMSE.SPCE3=sort(sub.data$PSEUDO.G.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.RMSE.SPCE3=sort(sub.data$IPW.UNTRIM.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$IPW.MAO.RMSE.SPCE3=sort(sub.data$IPW.MAO.RMSE.SPCE3,decreasing = if.decreasing)
sub.data$OW.MAO.RMSE.SPCE3=sort(sub.data$OW.MAO.RMSE.SPCE3,decreasing = if.decreasing)

sub.data$OW.BIAS.ASCE3=sort(sub.data$OW.BIAS.ASCE3, decreasing = if.decreasing)
sub.data$IPW.BIAS.ASCE3=sort(sub.data$IPW.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.ASCE3=sort(sub.data$COX.Q.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.ASCE3=sort(sub.data$COX.MSM.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.ASCE3=sort(sub.data$OW.AIPW.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.ASCE3=sort(sub.data$IPW.AIPW.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$OWG.BIAS.ASCE3=sort(sub.data$OWG.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$IPWG.BIAS.ASCE3=sort(sub.data$IPWG.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.BIAS.ASCE3=sort(sub.data$PSEUDO.UNADJ.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$PSEUDO.G.BIAS.ASCE3=sort(sub.data$PSEUDO.G.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.BIAS.ASCE3=sort(sub.data$IPW.UNTRIM.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$IPW.MAO.BIAS.ASCE3=sort(sub.data$IPW.MAO.BIAS.ASCE3,decreasing = if.decreasing)
sub.data$OW.MAO.BIAS.ASCE3=sort(sub.data$OW.MAO.BIAS.ASCE3,decreasing = if.decreasing)

sub.data$OW.BIAS.RACE3=sort(sub.data$OW.BIAS.RACE3, decreasing = if.decreasing)
sub.data$IPW.BIAS.RACE3=sort(sub.data$IPW.BIAS.RACE3,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.RACE3=sort(sub.data$COX.Q.BIAS.RACE3,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.RACE3=sort(sub.data$COX.MSM.BIAS.RACE3,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.RACE3=sort(sub.data$OW.AIPW.BIAS.RACE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.RACE3=sort(sub.data$IPW.AIPW.BIAS.RACE3,decreasing = if.decreasing)
sub.data$OWG.BIAS.RACE3=sort(sub.data$OWG.BIAS.RACE3,decreasing = if.decreasing)
sub.data$IPWG.BIAS.RACE3=sort(sub.data$IPWG.BIAS.RACE3,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.BIAS.RACE3=sort(sub.data$PSEUDO.UNADJ.BIAS.RACE3,decreasing = if.decreasing)
sub.data$PSEUDO.G.BIAS.RACE3=sort(sub.data$PSEUDO.G.BIAS.RACE3,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.BIAS.RACE3=sort(sub.data$IPW.UNTRIM.BIAS.RACE3,decreasing = if.decreasing)
sub.data$IPW.MAO.BIAS.RACE3=sort(sub.data$IPW.MAO.BIAS.RACE3,decreasing = if.decreasing)
sub.data$OW.MAO.BIAS.RACE3=sort(sub.data$OW.MAO.BIAS.RACE3,decreasing = if.decreasing)

sub.data$OW.BIAS.SPCE3=sort(sub.data$OW.BIAS.SPCE3, decreasing = if.decreasing)
sub.data$IPW.BIAS.SPCE3=sort(sub.data$IPW.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.SPCE3=sort(sub.data$COX.Q.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.SPCE3=sort(sub.data$COX.MSM.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.SPCE3=sort(sub.data$OW.AIPW.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.SPCE3=sort(sub.data$IPW.AIPW.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$OWG.BIAS.SPCE3=sort(sub.data$OWG.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$IPWG.BIAS.SPCE3=sort(sub.data$IPWG.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.BIAS.SPCE3=sort(sub.data$PSEUDO.UNADJ.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$PSEUDO.G.BIAS.SPCE3=sort(sub.data$PSEUDO.G.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.BIAS.SPCE3=sort(sub.data$IPW.UNTRIM.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$IPW.MAO.BIAS.SPCE3=sort(sub.data$IPW.MAO.BIAS.SPCE3,decreasing = if.decreasing)
sub.data$OW.MAO.BIAS.SPCE3=sort(sub.data$OW.MAO.BIAS.SPCE3,decreasing = if.decreasing)

sub.data$OW.COVER.ASCE3=cover.order(sub.data$OW.COVER.ASCE3, if.decreasing)
sub.data$IPW.COVER.ASCE3=cover.order(sub.data$IPW.COVER.ASCE3, if.decreasing)
sub.data$COX.Q.COVER.ASCE3=cover.order(sub.data$COX.Q.COVER.ASCE3, if.decreasing)
sub.data$COX.MSM.COVER.ASCE3=cover.order(sub.data$COX.MSM.COVER.ASCE3, if.decreasing)
sub.data$OW.AIPW.COVER.ASCE3=cover.order(sub.data$OW.AIPW.COVER.ASCE3, if.decreasing)
sub.data$IPW.AIPW.COVER.ASCE3=cover.order(sub.data$IPW.AIPW.COVER.ASCE3, if.decreasing)
sub.data$OWG.COVER.ASCE3=cover.order(sub.data$OWG.COVER.ASCE3, if.decreasing)
sub.data$IPWG.COVER.ASCE3=cover.order(sub.data$IPWG.COVER.ASCE3, if.decreasing)
sub.data$PSEUDO.UNADJ.COVER.ASCE3=cover.order(sub.data$PSEUDO.UNADJ.COVER.ASCE3,if.decreasing)
sub.data$PSEUDO.G.COVER.ASCE3=cover.order(sub.data$PSEUDO.G.COVER.ASCE3,if.decreasing)
sub.data$IPW.UNTRIM.COVER.ASCE3=cover.order(sub.data$IPW.UNTRIM.COVER.ASCE3,decreasing = if.decreasing)
sub.data$IPW.MAO.COVER.ASCE3=cover.order(sub.data$IPW.MAO.COVER.ASCE3,decreasing = if.decreasing)
sub.data$OW.MAO.COVER.ASCE3=cover.order(sub.data$OW.MAO.COVER.ASCE3,decreasing = if.decreasing)

sub.data$OW.COVER.RACE3=cover.order(sub.data$OW.COVER.RACE3, if.decreasing)
sub.data$IPW.COVER.RACE3=cover.order(sub.data$IPW.COVER.RACE3, if.decreasing)
sub.data$COX.Q.COVER.RACE3=cover.order(sub.data$COX.Q.COVER.RACE3, if.decreasing)
sub.data$COX.MSM.COVER.RACE3=cover.order(sub.data$COX.MSM.COVER.RACE3, if.decreasing)
sub.data$OW.AIPW.COVER.RACE3=cover.order(sub.data$OW.AIPW.COVER.RACE3, if.decreasing)
sub.data$IPW.AIPW.COVER.RACE3=cover.order(sub.data$IPW.AIPW.COVER.RACE3, if.decreasing)
sub.data$OWG.COVER.RACE3=cover.order(sub.data$OWG.COVER.RACE3, if.decreasing)
sub.data$IPWG.COVER.RACE3=cover.order(sub.data$IPWG.COVER.RACE3, if.decreasing)
sub.data$PSEUDO.UNADJ.COVER.RACE3=cover.order(sub.data$PSEUDO.UNADJ.COVER.RACE3,decreasing = if.decreasing)
sub.data$PSEUDO.G.COVER.RACE3=cover.order(sub.data$PSEUDO.G.COVER.RACE3,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.COVER.RACE3=cover.order(sub.data$IPW.UNTRIM.COVER.RACE3,decreasing = if.decreasing)
sub.data$IPW.MAO.COVER.RACE3=cover.order(sub.data$IPW.MAO.COVER.RACE3,decreasing = if.decreasing)
sub.data$OW.MAO.COVER.RACE3=cover.order(sub.data$OW.MAO.COVER.RACE3,decreasing = if.decreasing)

sub.data$OW.COVER.SPCE3=cover.order(sub.data$OW.COVER.SPCE3, if.decreasing)
sub.data$IPW.COVER.SPCE3=cover.order(sub.data$IPW.COVER.SPCE3, if.decreasing)
sub.data$COX.Q.COVER=cover.order(sub.data$COX.Q.COVER.SPCE3, if.decreasing)
sub.data$COX.MSM.COVER.SPCE3=cover.order(sub.data$COX.MSM.COVER.SPCE3, if.decreasing)
sub.data$OW.AIPW.COVER.SPCE3=cover.order(sub.data$OW.AIPW.COVER.SPCE3, if.decreasing)
sub.data$IPW.AIPW.COVER.SPCE3=cover.order(sub.data$IPW.AIPW.COVER.SPCE3, if.decreasing)
sub.data$OWG.COVER.SPCE3=cover.order(sub.data$OWG.COVER.SPCE3, if.decreasing)
sub.data$IPWG.COVER.SPCE3=cover.order(sub.data$IPWG.COVER.SPCE3, if.decreasing)
sub.data$PSEUDO.UNADJ.COVER.SPCE3=cover.order(sub.data$PSEUDO.UNADJ.COVER.SPCE3,decreasing = if.decreasing)
sub.data$PSEUDO.G.COVER.SPCE3=cover.order(sub.data$PSEUDO.G.COVER.SPCE3,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.COVER.SPCE3=cover.order(sub.data$IPW.UNTRIM.COVER.SPCE3,decreasing = if.decreasing)
sub.data$IPW.MAO.COVER.SPCE3=cover.order(sub.data$IPW.MAO.COVER.SPCE3,decreasing = if.decreasing)
sub.data$OW.MAO.COVER.SPCE3=cover.order(sub.data$OW.MAO.COVER.SPCE3,decreasing = if.decreasing)


# sub.data$OW.RMSE.ASCE2=sort(sub.data$OW.RMSE.ASCE2, decreasing = if.decreasing)
# sub.data$IPW.RMSE.ASCE2=sort(sub.data$IPW.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$COX.Q.RMSE.ASCE2=sort(sub.data$COX.Q.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$COX.MSM.RMSE.ASCE2=sort(sub.data$COX.MSM.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$OW.AIPW.RMSE.ASCE2=sort(sub.data$OW.AIPW.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$IPW.AIPW.RMSE.ASCE2=sort(sub.data$IPW.AIPW.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$OWG.RMSE.ASCE2=sort(sub.data$OWG.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$IPWG.RMSE.ASCE2=sort(sub.data$IPWG.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.UNADJ.RMSE.ASCE2=sort(sub.data$PSEUDO.UNADJ.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.G.RMSE.ASCE2=sort(sub.data$PSEUDO.G.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$IPW.UNTRIM.RMSE.ASCE2=sort(sub.data$IPW.UNTRIM.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.RMSE.ASCE2=sort(sub.data$IPW.MAO.RMSE.ASCE2,decreasing = if.decreasing)
# sub.data$OW.MAO.RMSE.ASCE2=sort(sub.data$OW.MAO.RMSE.ASCE2,decreasing = if.decreasing)
# 
# 
# sub.data$OW.RMSE.RACE2=sort(sub.data$OW.RMSE.RACE2, decreasing = if.decreasing)
# sub.data$IPW.RMSE.RACE2=sort(sub.data$IPW.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$COX.Q.RMSE.RACE2=sort(sub.data$COX.Q.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$COX.MSM.RMSE.RACE2=sort(sub.data$COX.MSM.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$OW.AIPW.RMSE.RACE2=sort(sub.data$OW.AIPW.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$IPW.AIPW.RMSE.RACE2=sort(sub.data$IPW.AIPW.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$OWG.RMSE.RACE2=sort(sub.data$OWG.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$IPWG.RMSE.RACE2=sort(sub.data$IPWG.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$PSEUDO.UNADJ.RMSE.RACE2=sort(sub.data$PSEUDO.UNADJ.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$PSEUDO.G.RMSE.RACE2=sort(sub.data$PSEUDO.G.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$IPW.UNTRIM.RMSE.RACE2=sort(sub.data$IPW.UNTRIM.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.RMSE.RACE2=sort(sub.data$IPW.MAO.RMSE.RACE2,decreasing = if.decreasing)
# sub.data$OW.MAO.RMSE.RACE2=sort(sub.data$OW.MAO.RMSE.RACE2,decreasing = if.decreasing)
# 
# sub.data$OW.RMSE.SPCE2=sort(sub.data$OW.RMSE.SPCE2, decreasing = if.decreasing)
# sub.data$IPW.RMSE.SPCE2=sort(sub.data$IPW.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$COX.Q.RMSE.SPCE2=sort(sub.data$COX.Q.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$COX.MSM.RMSE.SPCE2=sort(sub.data$COX.MSM.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$OW.AIPW.RMSE.SPCE2=sort(sub.data$OW.AIPW.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$IPW.AIPW.RMSE.SPCE2=sort(sub.data$IPW.AIPW.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$OWG.RMSE.SPCE2=sort(sub.data$OWG.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$IPWG.RMSE.SPCE2=sort(sub.data$IPWG.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.UNADJ.RMSE.SPCE2=sort(sub.data$PSEUDO.UNADJ.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.G.RMSE.SPCE2=sort(sub.data$PSEUDO.G.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$IPW.UNTRIM.RMSE.SPCE2=sort(sub.data$IPW.UNTRIM.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.RMSE.SPCE2=sort(sub.data$IPW.MAO.RMSE.SPCE2,decreasing = if.decreasing)
# sub.data$OW.MAO.RMSE.SPCE2=sort(sub.data$OW.MAO.RMSE.SPCE2,decreasing = if.decreasing)
# 
# sub.data$OW.BIAS.ASCE2=sort(sub.data$OW.BIAS.ASCE2, decreasing = if.decreasing)
# sub.data$IPW.BIAS.ASCE2=sort(sub.data$IPW.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$COX.Q.BIAS.ASCE2=sort(sub.data$COX.Q.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$COX.MSM.BIAS.ASCE2=sort(sub.data$COX.MSM.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$OW.AIPW.BIAS.ASCE2=sort(sub.data$OW.AIPW.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$IPW.AIPW.BIAS.ASCE2=sort(sub.data$IPW.AIPW.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$OWG.BIAS.ASCE2=sort(sub.data$OWG.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$IPWG.BIAS.ASCE2=sort(sub.data$IPWG.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.UNADJ.BIAS.ASCE2=sort(sub.data$PSEUDO.UNADJ.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.G.BIAS.ASCE2=sort(sub.data$PSEUDO.G.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$IPW.UNTRIM.BIAS.ASCE2=sort(sub.data$IPW.UNTRIM.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.BIAS.ASCE2=sort(sub.data$IPW.MAO.BIAS.ASCE2,decreasing = if.decreasing)
# sub.data$OW.MAO.BIAS.ASCE2=sort(sub.data$OW.MAO.BIAS.ASCE2,decreasing = if.decreasing)
# 
# sub.data$OW.BIAS.RACE2=sort(sub.data$OW.BIAS.RACE2, decreasing = if.decreasing)
# sub.data$IPW.BIAS.RACE2=sort(sub.data$IPW.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$COX.Q.BIAS.RACE2=sort(sub.data$COX.Q.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$COX.MSM.BIAS.RACE2=sort(sub.data$COX.MSM.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$OW.AIPW.BIAS.RACE2=sort(sub.data$OW.AIPW.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$IPW.AIPW.BIAS.RACE2=sort(sub.data$IPW.AIPW.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$OWG.BIAS.RACE2=sort(sub.data$OWG.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$IPWG.BIAS.RACE2=sort(sub.data$IPWG.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$PSEUDO.UNADJ.BIAS.RACE2=sort(sub.data$PSEUDO.UNADJ.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$PSEUDO.G.BIAS.RACE2=sort(sub.data$PSEUDO.G.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$IPW.UNTRIM.BIAS.RACE2=sort(sub.data$IPW.UNTRIM.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.BIAS.RACE2=sort(sub.data$IPW.MAO.BIAS.RACE2,decreasing = if.decreasing)
# sub.data$OW.MAO.BIAS.RACE2=sort(sub.data$OW.MAO.BIAS.RACE2,decreasing = if.decreasing)
# 
# sub.data$OW.BIAS.SPCE2=sort(sub.data$OW.BIAS.SPCE2, decreasing = if.decreasing)
# sub.data$IPW.BIAS.SPCE2=sort(sub.data$IPW.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$COX.Q.BIAS.SPCE2=sort(sub.data$COX.Q.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$COX.MSM.BIAS.SPCE2=sort(sub.data$COX.MSM.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$OW.AIPW.BIAS.SPCE2=sort(sub.data$OW.AIPW.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$IPW.AIPW.BIAS.SPCE2=sort(sub.data$IPW.AIPW.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$OWG.BIAS.SPCE2=sort(sub.data$OWG.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$IPWG.BIAS.SPCE2=sort(sub.data$IPWG.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.UNADJ.BIAS.SPCE2=sort(sub.data$PSEUDO.UNADJ.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.G.BIAS.SPCE2=sort(sub.data$PSEUDO.G.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$IPW.UNTRIM.BIAS.SPCE2=sort(sub.data$IPW.UNTRIM.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.BIAS.SPCE2=sort(sub.data$IPW.MAO.BIAS.SPCE2,decreasing = if.decreasing)
# sub.data$OW.MAO.BIAS.SPCE2=sort(sub.data$OW.MAO.BIAS.SPCE2,decreasing = if.decreasing)
# 
# sub.data$OW.COVER.ASCE2=cover.order(sub.data$OW.COVER.ASCE2, if.decreasing)
# sub.data$IPW.COVER.ASCE2=cover.order(sub.data$IPW.COVER.ASCE2, if.decreasing)
# sub.data$COX.Q.COVER.ASCE2=cover.order(sub.data$COX.Q.COVER.ASCE2, if.decreasing)
# sub.data$COX.MSM.COVER.ASCE2=cover.order(sub.data$COX.MSM.COVER.ASCE2, if.decreasing)
# sub.data$OW.AIPW.COVER.ASCE2=cover.order(sub.data$OW.AIPW.COVER.ASCE2, if.decreasing)
# sub.data$IPW.AIPW.COVER.ASCE2=cover.order(sub.data$IPW.AIPW.COVER.ASCE2, if.decreasing)
# sub.data$OWG.COVER.ASCE2=cover.order(sub.data$OWG.COVER.ASCE2, if.decreasing)
# sub.data$IPWG.COVER.ASCE2=cover.order(sub.data$IPWG.COVER.ASCE2, if.decreasing)
# sub.data$PSEUDO.UNADJ.COVER.ASCE2=cover.order(sub.data$PSEUDO.UNADJ.COVER.ASCE2,if.decreasing)
# sub.data$PSEUDO.G.COVER.ASCE2=cover.order(sub.data$PSEUDO.G.COVER.ASCE2,if.decreasing)
# sub.data$IPW.UNTRIM.COVER.ASCE2=cover.order(sub.data$IPW.UNTRIM.COVER.ASCE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.COVER.ASCE2=cover.order(sub.data$IPW.MAO.COVER.ASCE2,decreasing = if.decreasing)
# sub.data$OW.MAO.COVER.ASCE2=cover.order(sub.data$OW.MAO.COVER.ASCE2,decreasing = if.decreasing)
# 
# sub.data$OW.COVER.RACE2=cover.order(sub.data$OW.COVER.RACE2, if.decreasing)
# sub.data$IPW.COVER.RACE2=cover.order(sub.data$IPW.COVER.RACE2, if.decreasing)
# sub.data$COX.Q.COVER.RACE2=cover.order(sub.data$COX.Q.COVER.RACE2, if.decreasing)
# sub.data$COX.MSM.COVER.RACE2=cover.order(sub.data$COX.MSM.COVER.RACE2, if.decreasing)
# sub.data$OW.AIPW.COVER.RACE2=cover.order(sub.data$OW.AIPW.COVER.RACE2, if.decreasing)
# sub.data$IPW.AIPW.COVER.RACE2=cover.order(sub.data$IPW.AIPW.COVER.RACE2, if.decreasing)
# sub.data$OWG.COVER.RACE2=cover.order(sub.data$OWG.COVER.RACE2, if.decreasing)
# sub.data$IPWG.COVER.RACE2=cover.order(sub.data$IPWG.COVER.RACE2, if.decreasing)
# sub.data$PSEUDO.UNADJ.COVER.RACE2=cover.order(sub.data$PSEUDO.UNADJ.COVER.RACE2,decreasing = if.decreasing)
# sub.data$PSEUDO.G.COVER.RACE2=cover.order(sub.data$PSEUDO.G.COVER.RACE2,decreasing = if.decreasing)
# sub.data$IPW.UNTRIM.COVER.RACE2=cover.order(sub.data$IPW.UNTRIM.COVER.RACE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.COVER.RACE2=cover.order(sub.data$IPW.MAO.COVER.RACE2,decreasing = if.decreasing)
# sub.data$OW.MAO.COVER.RACE2=cover.order(sub.data$OW.MAO.COVER.RACE2,decreasing = if.decreasing)
# 
# sub.data$OW.COVER.SPCE2=cover.order(sub.data$OW.COVER.SPCE2, if.decreasing)
# sub.data$IPW.COVER.SPCE2=cover.order(sub.data$IPW.COVER.SPCE2, if.decreasing)
# sub.data$COX.Q.COVER=cover.order(sub.data$COX.Q.COVER.SPCE2, if.decreasing)
# sub.data$COX.MSM.COVER.SPCE2=cover.order(sub.data$COX.MSM.COVER.SPCE2, if.decreasing)
# sub.data$OW.AIPW.COVER.SPCE2=cover.order(sub.data$OW.AIPW.COVER.SPCE2, if.decreasing)
# sub.data$IPW.AIPW.COVER.SPCE2=cover.order(sub.data$IPW.AIPW.COVER.SPCE2, if.decreasing)
# sub.data$OWG.COVER.SPCE2=cover.order(sub.data$OWG.COVER.SPCE2, if.decreasing)
# sub.data$IPWG.COVER.SPCE2=cover.order(sub.data$IPWG.COVER.SPCE2, if.decreasing)
# sub.data$PSEUDO.UNADJ.COVER.SPCE2=cover.order(sub.data$PSEUDO.UNADJ.COVER.SPCE2,decreasing = if.decreasing)
# sub.data$PSEUDO.G.COVER.SPCE2=cover.order(sub.data$PSEUDO.G.COVER.SPCE2,decreasing = if.decreasing)
# sub.data$IPW.UNTRIM.COVER.SPCE2=cover.order(sub.data$IPW.UNTRIM.COVER.SPCE2,decreasing = if.decreasing)
# sub.data$IPW.MAO.COVER.SPCE2=cover.order(sub.data$IPW.MAO.COVER.SPCE2,decreasing = if.decreasing)
# sub.data$OW.MAO.COVER.SPCE2=cover.order(sub.data$OW.MAO.COVER.SPCE2,decreasing = if.decreasing)

sub.data$OW.RMSE.ASCE1=sort(sub.data$OW.RMSE.ASCE1, decreasing = if.decreasing)
sub.data$IPW.RMSE.ASCE1=sort(sub.data$IPW.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.ASCE1=sort(sub.data$COX.Q.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.ASCE1=sort(sub.data$COX.MSM.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.ASCE1=sort(sub.data$OW.AIPW.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.ASCE1=sort(sub.data$IPW.AIPW.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$OWG.RMSE.ASCE1=sort(sub.data$OWG.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$IPWG.RMSE.ASCE1=sort(sub.data$IPWG.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.RMSE.ASCE1=sort(sub.data$PSEUDO.UNADJ.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$PSEUDO.G.RMSE.ASCE1=sort(sub.data$PSEUDO.G.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.RMSE.ASCE1=sort(sub.data$IPW.UNTRIM.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$IPW.MAO.RMSE.ASCE1=sort(sub.data$IPW.MAO.RMSE.ASCE1,decreasing = if.decreasing)
sub.data$OW.MAO.RMSE.ASCE1=sort(sub.data$OW.MAO.RMSE.ASCE1,decreasing = if.decreasing)


sub.data$OW.RMSE.RACE1=sort(sub.data$OW.RMSE.RACE1, decreasing = if.decreasing)
sub.data$IPW.RMSE.RACE1=sort(sub.data$IPW.RMSE.RACE1,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.RACE1=sort(sub.data$COX.Q.RMSE.RACE1,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.RACE1=sort(sub.data$COX.MSM.RMSE.RACE1,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.RACE1=sort(sub.data$OW.AIPW.RMSE.RACE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.RACE1=sort(sub.data$IPW.AIPW.RMSE.RACE1,decreasing = if.decreasing)
sub.data$OWG.RMSE.RACE1=sort(sub.data$OWG.RMSE.RACE1,decreasing = if.decreasing)
sub.data$IPWG.RMSE.RACE1=sort(sub.data$IPWG.RMSE.RACE1,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.RMSE.RACE1=sort(sub.data$PSEUDO.UNADJ.RMSE.RACE1,decreasing = if.decreasing)
sub.data$PSEUDO.G.RMSE.RACE1=sort(sub.data$PSEUDO.G.RMSE.RACE1,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.RMSE.RACE1=sort(sub.data$IPW.UNTRIM.RMSE.RACE1,decreasing = if.decreasing)
sub.data$IPW.MAO.RMSE.RACE1=sort(sub.data$IPW.MAO.RMSE.RACE1,decreasing = if.decreasing)
sub.data$OW.MAO.RMSE.RACE1=sort(sub.data$OW.MAO.RMSE.RACE1,decreasing = if.decreasing)

sub.data$OW.RMSE.SPCE1=sort(sub.data$OW.RMSE.SPCE1, decreasing = if.decreasing)
sub.data$IPW.RMSE.SPCE1=sort(sub.data$IPW.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$COX.Q.RMSE.SPCE1=sort(sub.data$COX.Q.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$COX.MSM.RMSE.SPCE1=sort(sub.data$COX.MSM.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$OW.AIPW.RMSE.SPCE1=sort(sub.data$OW.AIPW.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.RMSE.SPCE1=sort(sub.data$IPW.AIPW.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$OWG.RMSE.SPCE1=sort(sub.data$OWG.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$IPWG.RMSE.SPCE1=sort(sub.data$IPWG.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.RMSE.SPCE1=sort(sub.data$PSEUDO.UNADJ.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$PSEUDO.G.RMSE.SPCE1=sort(sub.data$PSEUDO.G.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.RMSE.SPCE1=sort(sub.data$IPW.UNTRIM.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$IPW.MAO.RMSE.SPCE1=sort(sub.data$IPW.MAO.RMSE.SPCE1,decreasing = if.decreasing)
sub.data$OW.MAO.RMSE.SPCE1=sort(sub.data$OW.MAO.RMSE.SPCE1,decreasing = if.decreasing)

sub.data$OW.BIAS.ASCE1=sort(sub.data$OW.BIAS.ASCE1, decreasing = if.decreasing)
sub.data$IPW.BIAS.ASCE1=sort(sub.data$IPW.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.ASCE1=sort(sub.data$COX.Q.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.ASCE1=sort(sub.data$COX.MSM.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.ASCE1=sort(sub.data$OW.AIPW.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.ASCE1=sort(sub.data$IPW.AIPW.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$OWG.BIAS.ASCE1=sort(sub.data$OWG.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$IPWG.BIAS.ASCE1=sort(sub.data$IPWG.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.BIAS.ASCE1=sort(sub.data$PSEUDO.UNADJ.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$PSEUDO.G.BIAS.ASCE1=sort(sub.data$PSEUDO.G.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.BIAS.ASCE1=sort(sub.data$IPW.UNTRIM.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$IPW.MAO.BIAS.ASCE1=sort(sub.data$IPW.MAO.BIAS.ASCE1,decreasing = if.decreasing)
sub.data$OW.MAO.BIAS.ASCE1=sort(sub.data$OW.MAO.BIAS.ASCE1,decreasing = if.decreasing)

sub.data$OW.BIAS.RACE1=sort(sub.data$OW.BIAS.RACE1, decreasing = if.decreasing)
sub.data$IPW.BIAS.RACE1=sort(sub.data$IPW.BIAS.RACE1,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.RACE1=sort(sub.data$COX.Q.BIAS.RACE1,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.RACE1=sort(sub.data$COX.MSM.BIAS.RACE1,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.RACE1=sort(sub.data$OW.AIPW.BIAS.RACE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.RACE1=sort(sub.data$IPW.AIPW.BIAS.RACE1,decreasing = if.decreasing)
sub.data$OWG.BIAS.RACE1=sort(sub.data$OWG.BIAS.RACE1,decreasing = if.decreasing)
sub.data$IPWG.BIAS.RACE1=sort(sub.data$IPWG.BIAS.RACE1,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.BIAS.RACE1=sort(sub.data$PSEUDO.UNADJ.BIAS.RACE1,decreasing = if.decreasing)
sub.data$PSEUDO.G.BIAS.RACE1=sort(sub.data$PSEUDO.G.BIAS.RACE1,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.BIAS.RACE1=sort(sub.data$IPW.UNTRIM.BIAS.RACE1,decreasing = if.decreasing)
sub.data$IPW.MAO.BIAS.RACE1=sort(sub.data$IPW.MAO.BIAS.RACE1,decreasing = if.decreasing)
sub.data$OW.MAO.BIAS.RACE1=sort(sub.data$OW.MAO.BIAS.RACE1,decreasing = if.decreasing)

sub.data$OW.BIAS.SPCE1=sort(sub.data$OW.BIAS.SPCE1, decreasing = if.decreasing)
sub.data$IPW.BIAS.SPCE1=sort(sub.data$IPW.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$COX.Q.BIAS.SPCE1=sort(sub.data$COX.Q.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$COX.MSM.BIAS.SPCE1=sort(sub.data$COX.MSM.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$OW.AIPW.BIAS.SPCE1=sort(sub.data$OW.AIPW.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$IPW.AIPW.BIAS.SPCE1=sort(sub.data$IPW.AIPW.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$OWG.BIAS.SPCE1=sort(sub.data$OWG.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$IPWG.BIAS.SPCE1=sort(sub.data$IPWG.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$PSEUDO.UNADJ.BIAS.SPCE1=sort(sub.data$PSEUDO.UNADJ.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$PSEUDO.G.BIAS.SPCE1=sort(sub.data$PSEUDO.G.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.BIAS.SPCE1=sort(sub.data$IPW.UNTRIM.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$IPW.MAO.BIAS.SPCE1=sort(sub.data$IPW.MAO.BIAS.SPCE1,decreasing = if.decreasing)
sub.data$OW.MAO.BIAS.SPCE1=sort(sub.data$OW.MAO.BIAS.SPCE1,decreasing = if.decreasing)

sub.data$OW.COVER.ASCE1=cover.order(sub.data$OW.COVER.ASCE1, if.decreasing)
sub.data$IPW.COVER.ASCE1=cover.order(sub.data$IPW.COVER.ASCE1, if.decreasing)
sub.data$COX.Q.COVER.ASCE1=cover.order(sub.data$COX.Q.COVER.ASCE1, if.decreasing)
sub.data$COX.MSM.COVER.ASCE1=cover.order(sub.data$COX.MSM.COVER.ASCE1, if.decreasing)
sub.data$OW.AIPW.COVER.ASCE1=cover.order(sub.data$OW.AIPW.COVER.ASCE1, if.decreasing)
sub.data$IPW.AIPW.COVER.ASCE1=cover.order(sub.data$IPW.AIPW.COVER.ASCE1, if.decreasing)
sub.data$OWG.COVER.ASCE1=cover.order(sub.data$OWG.COVER.ASCE1, if.decreasing)
sub.data$IPWG.COVER.ASCE1=cover.order(sub.data$IPWG.COVER.ASCE1, if.decreasing)
sub.data$PSEUDO.UNADJ.COVER.ASCE1=cover.order(sub.data$PSEUDO.UNADJ.COVER.ASCE1,if.decreasing)
sub.data$PSEUDO.G.COVER.ASCE1=cover.order(sub.data$PSEUDO.G.COVER.ASCE1,if.decreasing)
sub.data$IPW.UNTRIM.COVER.ASCE1=cover.order(sub.data$IPW.UNTRIM.COVER.ASCE1,decreasing = if.decreasing)
sub.data$IPW.MAO.COVER.ASCE1=cover.order(sub.data$IPW.MAO.COVER.ASCE1,decreasing = if.decreasing)
sub.data$OW.MAO.COVER.ASCE1=cover.order(sub.data$OW.MAO.COVER.ASCE1,decreasing = if.decreasing)

sub.data$OW.COVER.RACE1=cover.order(sub.data$OW.COVER.RACE1, if.decreasing)
sub.data$IPW.COVER.RACE1=cover.order(sub.data$IPW.COVER.RACE1, if.decreasing)
sub.data$COX.Q.COVER.RACE1=cover.order(sub.data$COX.Q.COVER.RACE1, if.decreasing)
sub.data$COX.MSM.COVER.RACE1=cover.order(sub.data$COX.MSM.COVER.RACE1, if.decreasing)
sub.data$OW.AIPW.COVER.RACE1=cover.order(sub.data$OW.AIPW.COVER.RACE1, if.decreasing)
sub.data$IPW.AIPW.COVER.RACE1=cover.order(sub.data$IPW.AIPW.COVER.RACE1, if.decreasing)
sub.data$OWG.COVER.RACE1=cover.order(sub.data$OWG.COVER.RACE1, if.decreasing)
sub.data$IPWG.COVER.RACE1=cover.order(sub.data$IPWG.COVER.RACE1, if.decreasing)
sub.data$PSEUDO.UNADJ.COVER.RACE1=cover.order(sub.data$PSEUDO.UNADJ.COVER.RACE1,decreasing = if.decreasing)
sub.data$PSEUDO.G.COVER.RACE1=cover.order(sub.data$PSEUDO.G.COVER.RACE1,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.COVER.RACE1=cover.order(sub.data$IPW.UNTRIM.COVER.RACE1,decreasing = if.decreasing)
sub.data$IPW.MAO.COVER.RACE1=cover.order(sub.data$IPW.MAO.COVER.RACE1,decreasing = if.decreasing)
sub.data$OW.MAO.COVER.RACE1=cover.order(sub.data$OW.MAO.COVER.RACE1,decreasing = if.decreasing)

sub.data$OW.COVER.SPCE1=cover.order(sub.data$OW.COVER.SPCE1, if.decreasing)
sub.data$IPW.COVER.SPCE1=cover.order(sub.data$IPW.COVER.SPCE1, if.decreasing)
sub.data$COX.Q.COVER=cover.order(sub.data$COX.Q.COVER.SPCE1, if.decreasing)
sub.data$COX.MSM.COVER.SPCE1=cover.order(sub.data$COX.MSM.COVER.SPCE1, if.decreasing)
sub.data$OW.AIPW.COVER.SPCE1=cover.order(sub.data$OW.AIPW.COVER.SPCE1, if.decreasing)
sub.data$IPW.AIPW.COVER.SPCE1=cover.order(sub.data$IPW.AIPW.COVER.SPCE1, if.decreasing)
sub.data$OWG.COVER.SPCE1=cover.order(sub.data$OWG.COVER.SPCE1, if.decreasing)
sub.data$IPWG.COVER.SPCE1=cover.order(sub.data$IPWG.COVER.SPCE1, if.decreasing)
sub.data$PSEUDO.UNADJ.COVER.SPCE1=cover.order(sub.data$PSEUDO.UNADJ.COVER.SPCE1,decreasing = if.decreasing)
sub.data$PSEUDO.G.COVER.SPCE1=cover.order(sub.data$PSEUDO.G.COVER.SPCE1,decreasing = if.decreasing)
sub.data$IPW.UNTRIM.COVER.SPCE1=cover.order(sub.data$IPW.UNTRIM.COVER.SPCE1,decreasing = if.decreasing)
sub.data$IPW.MAO.COVER.SPCE1=cover.order(sub.data$IPW.MAO.COVER.SPCE1,decreasing = if.decreasing)
sub.data$OW.MAO.COVER.SPCE1=cover.order(sub.data$OW.MAO.COVER.SPCE1,decreasing = if.decreasing)
