R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=1 sample_size=150' simu_main.R ALf1.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=2 sample_size=150' simu_main.R ALf2.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=3 sample_size=150' simu_main.R ALf3.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=1 sample_size=300' simu_main.R AMf1.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=2 sample_size=300' simu_main.R AMf2.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=3 sample_size=300' simu_main.R AMf3.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=1 sample_size=450' simu_main.R ALf4.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=2 sample_size=450' simu_main.R ALf5.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=3 sample_size=450' simu_main.R ALf6.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=1 sample_size=600' simu_main.R ALf7.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=2 sample_size=600' simu_main.R ALf8.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=3 sample_size=600' simu_main.R ALf9.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=1 sample_size=750' simu_main.R ALf10.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=2 sample_size=750' simu_main.R ALf11.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=F good_overlap=3 sample_size=750' simu_main.R ALf12.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=1 sample_size=150' simu_main.R ALt1.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=2 sample_size=150' simu_main.R ALt2.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=3 sample_size=150' simu_main.R ALt3.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=1 sample_size=300' simu_main.R AMf4.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=2 sample_size=300' simu_main.R AMf5.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=3 sample_size=300' simu_main.R AMf6ut &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=1 sample_size=450' simu_main.R ALt4.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=2 sample_size=450' simu_main.R ALt5.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=3 sample_size=450' simu_main.R ALt6.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=1 sample_size=600' simu_main.R ALt7.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=2 sample_size=600' simu_main.R ALt8.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=3 sample_size=600' simu_main.R ALt9.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=1 sample_size=750' simu_main.R ALt10.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=2 sample_size=750' simu_main.R ALt11.out &
R CMD BATCH --vanilla '--args dependent.censoring=F multi.arm=T prop.hazard=T good_overlap=3 sample_size=750' simu_main.R ALt12.out &

R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=F good_overlap=1 sample_size=300' simu_main.R df7.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=F good_overlap=2 sample_size=300' simu_main.R df8.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=F good_overlap=3 sample_size=300' simu_main.R df9.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=T good_overlap=1 sample_size=300' simu_main.R df10.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=T good_overlap=2 sample_size=300' simu_main.R df11.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=T good_overlap=3 sample_size=300' simu_main.R df12.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=F good_overlap=1 sample_size=150' simu_main.R df13.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=F good_overlap=2 sample_size=150' simu_main.R df14.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=F good_overlap=3 sample_size=150' simu_main.R df15.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=T good_overlap=1 sample_size=150' simu_main.R df16.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=T good_overlap=2 sample_size=150' simu_main.R df17.out &
R CMD BATCH --vanilla '--args dependent.censoring=T multi.arm=T prop.hazard=T good_overlap=3 sample_size=150' simu_main.R df18.out &
